import type { MetadataRoute } from 'next';

/**
 * PWA-style install hints. Icons are generated by `app/icon.tsx` and `app/apple-icon.tsx`.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Auto-Coder — Autonomous AI IDE',
    short_name: 'Auto-Coder',
    description:
      'The AI-powered IDE that plans, executes, tests, and self-heals. Web assistant, desktop IDE, and CLI.',
    start_url: '/',
    display: 'standalone',
    background_color: '#0d1117',
    theme_color: '#0d1117',
    orientation: 'any',
    categories: ['developer tools', 'productivity', 'utilities'],
    icons: [
      { src: '/icon', type: 'image/png', sizes: '32x32', purpose: 'any' },
      { src: '/apple-icon', type: 'image/png', sizes: '180x180', purpose: 'any' },
    ],
  };
}
